spring:
  datasource:
    url: jdbc:mysql://localhost:3306/camunda?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

camunda:
  bpm:
    admin-user:
      id: admin
      password: admin
    database:
      type: mysql
      schema-update: true
